/**
 * @type {import('express').RequestHandler}
 * leave a comment for a post
* For example: POST /comments
*             Payload: {
              content: 'hi',
              createdDate: ...
              updatedDate: ...
              userId: ...
              postId: ...
              replyTo: ...
              }
 */
export default async (req, res) => { }
